# Generated by Django 4.2 on 2024-05-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_processattendancedaily_ot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshift',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duraion'),
        ),
    ]
