# Generated by Django 4.2 on 2024-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffshift_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='processattendancedaily',
            name='actual_ot_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='actual_ot_duration'),
        ),
    ]
