# Generated by Django 4.2 on 2024-06-05 11:28

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_processstaffattendancemst'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstaffattendancemst',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processstaffattendancemst',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='processstaffattendancemst',
            name='code',
            field=models.CharField(default=staff.models.staff_atnn_code, editable=False, max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='processstaffattendancemst',
            name='total_day',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
