# Generated by Django 4.2 on 2024-06-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_processstaffattendancemst_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstaffattendancemst',
            name='tot_payble_day',
            field=models.IntegerField(default=0),
        ),
    ]
