# Generated by Django 4.2 on 2024-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_processstaffattendancemst_tot_payble_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstaffattendancemst',
            name='staff_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
