# Generated by Django 4.2 on 2024-12-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
