# Generated by Django 4.2 on 2024-05-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
