# Generated by Django 4.2 on 2024-07-16 04:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_app', '0002_activestatue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveStatue',
            new_name='ActiveStatus',
        ),
    ]
