# Generated by Django 4.2 on 2024-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0004_systemcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcounter',
            name='fiscal_year_as_prefix',
        ),
        migrations.AlterField(
            model_name='systemcounter',
            name='prefix',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
