# Generated by Django 4.2 on 2024-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0005_remove_systemcounter_fiscal_year_as_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcounter',
            name='counter_width',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
